# MINIO_ROOT_USER and MINIO_ROOT_PASSWORD sets the root account for the MinIO server.
# This user has unrestricted permissions to perform S3 and administrative API operations on any resource in the deployment.
# Omit to use the default values 'minioadmin:minioadmin'.
# MinIO recommends setting non-default values as a best practice, regardless of environment
# 设置控制台的账号及密码
MINIO_ROOT_USER=${MINIO_USERNAME}
MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}

# MINIO_VOLUMES sets the storage volume or path to use for the MinIO server.
MINIO_VOLUMES=${MINIO_DATA_DIR}

# MINIO_SERVER_URL sets the hostname of the local machine for use with the MinIO Server
# MinIO assumes your network control plane can correctly resolve this hostname to the local machine
# Uncomment the following line and replace the value with the correct hostname for the local machine and port for the MinIO server (9000 by default).
#MINIO_SERVER_URL="http://minio.example.net:9000"

# 设置9000为文件访问端口，9001为内嵌控制台页面访问端口
MINIO_OPTS="--address :9000  --console-address :9001"